/* ------- errs.c ------- */




char *errs[] = {
	"debug trap",
	"not a pointer",
	"not an address",
	"not a pointer or array",
	"not a struct pointer",
	"missing '}'",
	"unknown identifier",
	"file error",
	"missing '{'",
	"lexical error",
	"statement outside of function",
	"need an lvalue",
	"variable already declared",
	"stack underflow",
	"stack space exhausted",
	"missing ')' or ']'",
	"expression error",
	"syntax error",
	"expression nesting is too deep",
	"too many dimensions",
	"illegal pointer arithmetic",
	"invalid function call",
	"missing ';'",
	"not a struct or union",
	"not a struct or union element",
	"initialization error",
	"divide by 0",
	"size error",
	"break outside of loop",
	"continue outside of loop",
	"floating point error",
	"#defines nested too deeply",
	"#define error",
	"out of memory",
	"negative array dimension",
	"missing '('",
	"unexpected '(' or '['",
	"missing ':'",
	"missing while",
	"misplaced variable declaration",
	"misplaced comma",
	"enum error",
	"void functions may not return values",
	"argument mismatch error",
	"function should return something",
	"function redefinition error",
	"incompatible pointers",
	"unknown function",
	"missing identifer",
	"improper void * usage",
	"not a numeric type",
	"incompatible types",
	"unterminated comment",
	"type needed",
	"variable space exhausted",
	"function space exhausted",
	"data space exhausted",
	"longjmp without setjmp",
	"program interrupted",
	"line too long",
	"invalid preprocessor directive",
	"redefinition of macro",
	"#endif without #if",
	"#else without #if",
	"#elif without #if",
	"#include file not found",
	"#if, #ifdef, or #ifndef without #endif",
	"unterminated string literal",
	"unterminated character constant",
	"#if error",
	"mismatched macro arguments",
	"stdin redirection file error",
	"stdout redirection file error",
	"no main function",
	"symbol table full",
	"constant expression required",
	"unknown label",
	"else without if",
	"switch error",
	"default outside of switch",
	"case outside of switch",
	"too many defaults",
	"function name expected",
	"invalid typedef",
	"declaration error",
	"misplaced # in #define",
	"invalid pointer comparison",
	"integer type required",
	"math exception",
	"can't take address of register variable",
	"unresolved extern",
	"undefined function",
	"too many initializers",
	"const argument to non-const pointer",
	"#includes nested too deep",
	"#ifs nested too deep",
	"#error directive",
	"-----------------------------------------------------------------------"
};


