/* --- math.h --- */

#ifndef _MATH_H
#define _MATH_H

double acos(double);
double asin(double);
double atan(double);
double ceil(double);
double cos(double);
double cosh(double);
double exp(double);
double fabs(double);
double floor(double);
double sin(double);
double sinh(double);
double sqrt(double);
double tan(double);
double tanh(double);
double log(double);
double log10(double);
double pow(double,double);
double atan2(double,double);

#endif

